### PR TITLE
Operation errors patch

### LINKED ISSUE #210: Report operational errors
There are at least two ways the checker can fail to process a pull request:
* it doesn't recognize the repo (e.g. after a name change #64)
* the secret used to verify the origin of the check is wrong (which has happened a number of times, although I'm not sure how)

… and probably more. Right now, these failures are simply logged as a webook failure - useful for debugging, not for noticing there is a configuration issue.

These should instead be reported - either on the pull request itself, or on this repo (probably both - e.g. it could stay in "pending" state on the pull request status with an appropriate message, while reporting the issue here).

### PR DESCRIPTION
**Pull request by deniak**
That PR:
* updates the status of the PR to `failure` if the targeted repository is not known to the repository manager
* updates the [signature verification using sha256](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github)
* handles a promise rejection

Fix #210 

Regarding handling repository renaming, I made some [suggestions](https://github.com/w3c/ash-nazg/issues/64#issuecomment-882613167) we can discuss.

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -415,14 +418,39 @@ function addGHHook(app, path) {
...
+                        });
+                    } catch (e) {
+                        log.error(`Token not found for ${owner}`);
+                    }
+                    return error(res, "Secret for " + repo + " not found: " + (err || "simply not there."));
+                }
 
                 // we have the secret, crypto check becomes possible
-                if (!GH.checkPayloadSignature("sha1", data.secret, buffer, req.headers["x-hub-signature"])) return error(res, "GitHub signature does not match known secret for " + repo + ".");
+                if (!GH.checkPayloadSignature("sha256", data.secret, buffer, req.headers["x-hub-signature"])) return error(res, "GitHub signature does not match known secret for " + repo + ".");
```
Comment (dontcallmedom) [inline server.js:453]: can you say more about the change from sha1 to sha256? Is it backwards compatible with our existing data?

Comment (dontcallmedom) [reply server.js:453]: more specifically, if I understand https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github correctly, to use sha-256 we would need to take the signature from X-Hub-Signature-256

Comment (deniak) [reply server.js]: > more specifically, if I understand https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github correctly, to use sha-256 we would need to take the signature from X-Hub-Signature-256

That's correct, I forgot to update the header to be checked.
I started looking at the signature verification to see if the second issue you reported at https://github.com/w3c/ash-nazg/issues/210 wasn't related to that function. It doesn't seem to be the case but we could still follow the GH recommendation of using the SHA-256 signature. I understand this shouldn't break the existing data and the function will only check future payloads.

**Review by dontcallmedom — APPROVED** [review]
